services:

  api_build:
    build:
      context: .
      dockerfile: Dockerfile
    image: lab_api_build
    command: echo "Build conclu√≠do com sucesso!"

  api_test:
    build:
      context: .
      dockerfile: Dockerfile
    image: lab_api_test
    command: python -m unittest -v
    depends_on:
      api_build:
        condition: service_completed_successfully

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: lab_api
    container_name: lab_api_container
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
    command: flask run --host=0.0.0.0 --port=5000
    depends_on:
      api_test:
        condition: service_completed_successfully
